<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	  <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.7.0" />
	  <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
	  <PackageReference Include="Rebus.PostgreSql" Version="9.1.1" />
	  <PackageReference Include="Rebus.RabbitMq" Version="10.1.1" />
	  <PackageReference Include="Rebus.ServiceProvider" Version="10.1.0" />
	  <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ambev.DeveloperEvaluation.Domain\Ambev.DeveloperEvaluation.Domain.csproj" />
		<ProjectReference Include="..\Ambev.DeveloperEvaluation.Application\Ambev.DeveloperEvaluation.Application.csproj" />
		<ProjectReference Include="..\Ambev.DeveloperEvaluation.ORM\Ambev.DeveloperEvaluation.ORM.csproj" />
		<ProjectReference Include="..\Ambev.DeveloperEvaluation.Common\Ambev.DeveloperEvaluation.Common.csproj" />
	</ItemGroup>

</Project>
